### ISSUE TITLE
Subimos el tp1 terminado

### ISSUE THREAD

**Issue by frandom00** [frandom00/2020_K2001_Grupo_9#1]
@santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

Por favor leer correctamente la consigna del trabajo

1) Se debe implementar un AFD mediante una tabla de transición. El código cumple con la funcionalidad pero no implementa ningún autómata. Es parte de la consigna principal que carguen la tabla de transición como una matriz y vayan avanzando sobre la misma. Son cosas que comenté en la última clase que tuvimos. Por favor respetar la consigna.
2) El archivo de entrada es "entrada.txt" , el de salida "salida.txt"
3) Todo el trabajo debe estar en la carpeta TP_1 dentro de GitHub

Aguardo las correcciones para una nueva entrega si desean una mejor calificación

Nota: 6

Por favor cualquier duda o complicación me avisan

Saludos

Santiago

@frandom00 @melabelen @elenharu @tomasdeli @Leonel49

**Comment by frandom00** [comment]
Disculpe profe tenia el archivo viejo sin implementar matriz en la computadora y me confundi y subi ese, igualmente arreglamos el nombre del archivo de entrada y salida, lo que no se es si todo el trabajo esta en la carpeta de TP1
________________________________
De: Santiago Ferreiros Cabrera <notifications@github.com>
Enviado: sábado, 25 de abril de 2020 23:10
Para: frandom00/2020_K2001_Grupo_9 <2020_K2001_Grupo_9@noreply.github.com>
Cc: frandom00 <franciscoandresdominguez@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [frandom00/2020_K2001_Grupo_9] Subimos el tp1 terminado (#1)


Estimados,

Por favor leer correctamente la consigna del trabajo

  1.  Se debe implementar un AFD mediante una tabla de transición. El código cumple con la funcionalidad pero no implementa ningún autómata. Es parte de la consigna principal que carguen la tabla de transición como una matriz y vayan avanzando sobre la misma. Son cosas que comenté en la última clase que tuvimos. Por favor respetar la consigna.
  2.  El archivo de entrada es "entrada.txt" , el de salida "salida.txt"
  3.  Todo el trabajo debe estar en la carpeta TP_1 dentro de GitHub

Aguardo las correcciones para una nueva entrega si desean una mejor calificación

Nota: 6

Por favor cualquier duda o complicación me avisan

Saludos

Santiago

@frandom00<https://github.com/frandom00> @melabelen<https://github.com/melabelen> @elenharu<https://github.com/elenharu> @tomasdeli<https://github.com/tomasdeli> @Leonel49<https://github.com/Leonel49>
