### ISSUE TITLE
TP_1

### ISSUE THREAD

**Issue by frandom00** [frandom00/2020_K2001_Grupo_9#4]
@santiagoferreiros  Disculpe por tantos commits pero creo que ahi esta subido a la carpeta correcta

**Comment by santiagoferreiros** [comment]
Estimados,

El repositorio está lleno de archivos. No están cumpliendo las especificaciones. Sepan entender que tengo que corregir más de 25 trabajos prácticos y no me es viable estar buscando cual de todos los archivos .c es el indicado. Por favor, para la próxima les pido una entrega mucho más prolija o limpia. Cuando tengan todo listo manda el issue.

Intenté correr el último archivo subido pero no levanta el archivo entrada.txt y de hecho crea un archivo docEscribir, cuando debería ser salida.txt

Arreglen tranquilos el repositorio y me lo entregan cuando esté listo. No hay problema con el plazo. Haganlo tranquilos. 

Saludos :)
