### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by frandom00** [frandom00/2020_K2001_Grupo_9#5]
@santiagoferreiros profe tiene que entrar a la carpeta que se llama TP_1, ahi esta el main.c y el entrada.txt

**Comment by santiagoferreiros** [comment]
Estimados,

Ahí lo pude probar.
La última cadena la clasifica si después viene una "," antes del fin de archivo. La última cadena viene seguida de EOF, Sino las ves a quedar sin procesar, por lo que vi, en el archivo de entrada.txt para que reconozca la última cadena le han agregado una coma. Quizás lo puedan resolver con una condición más en el IF que pregunta si es "," o EOF.

Otra aclaración, en el archivo de salida debe indicar a cual corresponde cada clasificación. Es decir algo con el siguiente formato como indica el enunciado

012 --> Octal
0xFF --> Hexa
0x --> No reconocida

La entrega se encuentra aprobada,
Para la próxima instancia les pido mayor orden y prolijidad,
Felicitaciones y a seguir trabajando. Entiendan que estas observaciones son para que puedan mejorar sus trabajos y formarse.

Nota:  8

@frandom00 @melabelen @elenharu @tomasdeli @Leonel49
