### ISSUE TITLE
Entrega Trabajo Práctico N°2

### ISSUE THREAD

**Issue by frandom00** [frandom00/2020_K2001_Grupo_9#6]
Solicito correcion del trabajo practico Nº2 @santiagoferreiros; es el main.c que se encuentra en la carpeta correspondiente

**Comment by santiagoferreiros** [comment]
Estimados,

Muy buen trabajo !!

Nota: 9

La tabla de transición está implementada a medias. Indica el estado siguiente, pero no tiene guardada la información del push. Eso por lo que veo lo trabajaron en una función aparte. La idea es que la TT tenga toda la información del AFP.

De todos modos, muy buen trabajo ! Los felicito ! 
Y tenga presente eso para la próxima, cada elemento de la TT del AFP es un struct que tiene dos campos. ESTADO, CADENA_A_PUSHEAR, por ejemplo {1,"R$"}

Saludos =)

@frandom00 @melabelen @elenharu @tomasdeli
