### ISSUE TITLE
Entrega Trabajo Práctico Nº3

### ISSUE THREAD

**Issue by frandom00** [frandom00/2020_K2001_Grupo_9#7]
@santiagoferreiros entrego el TP3, esta igual que el del grupo 2 y tiene un error que no pudimos encontrar, por eso pense en no entregarlo hasta hacer que funcione bien, pero todavia no pudimos

**Comment by santiagoferreiros** [comment]
Estimado equipo

Si, veo que el trabajo de ustedes es similar al del grupo 2.
La entrega se va a considerar aprobada.

Les propongo que trabajen en conjunto para hacer andar el TP 3. Podrían delegar un miembro de cada grupo para resolverlo.

Y que el resto comience con el TP 4. Para el TP 4 solo es necesario tener OK las ERX. Pero para el integrador lo van a necesitar.

Saludos,

Santiago
